version: '3.8'
services:
  my5grantester:
    image: my5grantester:latest
    container_name: my5grantester
    privileged: true
    environment:
      NGAP_LOCAL_ADDR: 192.168.70.143
      NGAP_REMOTE_ADDR: 192.168.70.132
      GTPU_LOCAL_ADDR: 192.168.70.143
      MCC: 208
      MNC: 99
      TAC: 00a000
      GNBID: "000003"
      SST_GNB: de
      SST_UE: 222
      SD: "00007b"
      MSIN: "0000000002"
      OPC: C42449363BBAD02B66D16BC975D77CC1
      KEY: fec86ba6eb707ed08905757b1bb44b8f
      AMF: 8000
      SQN: 0000000
      DNN: oai
      NUM_UE: 1
    cap_add:
      - NET_ADMIN
    networks:
      public_net:
          ipv4_address: 192.168.70.143
    healthcheck:
      test: /bin/bash -c "ip addr | grep uetun1"
      interval: 10s
      timeout: 5s
      retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net

