apiVersion: athena.trirematics.io/v1
kind: Network
metadata:
    name: eurecom
    namespace: trirematics
spec:
    slices:
        -   plmn: "00102"
            dnn: "internet"
            network-mode: "IPv4"
            service-type: eMBB
            differentiator: 0x000000
            ipv4-range: "12.1.1.0/24"
            ipv6-range: "2001:db8:1::/64"
    access:
        -   name: srs-lte
            stack: 4g-sa
            model: srs/srs-enb
            profiles:
                - pcap
            identity:
                an-id: 50
            radio:
                device: rf-sim
            cells:
                -   band: b7
                    arfcn: 3350
                    bandwidth: 10MHz
                    subcarrier-spacing: 15kHz
            annotations:
                extras.trirematics.io/ue-sim: srs-ue
            core-networks:
                - core.eurecom
    core:
        -   name: core
            stack: 4g-sa
            model: srs/srs-epc
            identity:
                region: 0
                cn-group: 4
                cn-id: 5
    dns:
        ipv4:
            default: 8.8.8.8
            secondary: 8.8.4.4
---
apiVersion: athena.trirematics.io/v1
kind: Terminal
metadata:
    name: srs-ue
    namespace: trirematics
spec:
    vendor: srs
    stack: 4g-sa
    model: terminal/srs-sim
    preferred-access: srs-lte.eurecom
    target-cores:
        - core.eurecom
    identity:
        imsi: "001020000000001"
        pin: "1234"
        opc: "0xc42449363bbad02b66d16bc975d77cc1"
        key: "0xfec86ba6eb707ed08905757b1bb44b8f"
        sqn: "0xff9bb4000001"
    slice:
        dnn: "internet"
        network-mode: "IPv4"
        service-type: eMBB
        differentiator: 0x000000
    radio:
        bands:
            - b7
    readiness-check:
        method: ping
        ip: 12.1.1.1
        interface-name: srs-ue
