version: '3.8'
services:
  my5grantester4:
    image: my5grantester:latest
    container_name: my5grantester4
    privileged: true
    environment:
      NGAP_LOCAL_ADDR: 192.168.70.150
      NGAP_REMOTE_ADDR: 192.168.70.132
      GTPU_LOCAL_ADDR: 192.168.70.150
      MCC: 208
      MNC: 98
      TAC: 00ab00
      GNBID: "000003"
      SST_GNB: a1
      SST_UE: 161
      SD: "00009c"
      MSIN: "0000000004"
      OPC: 63bfa50ee6523365ff14c1f45f88737d
      KEY: 0C0A34601D4F07677303652C0462535B
      AMF: 8000
      SQN: 0000000
      DNN: oai
      NUM_UE: 1
    cap_add:
      - NET_ADMIN
    networks:
      public_net:
          ipv4_address: 192.168.70.150
    healthcheck:
      test: /bin/bash -c "ip addr | grep uetun1"
      interval: 10s
      timeout: 5s
      retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net

