version: '3.8'
services:
  my5grantester3:
    image: my5grantester:latest
    container_name: my5grantester3
    privileged: true
    environment:
      NGAP_LOCAL_ADDR: 192.168.70.151
      NGAP_REMOTE_ADDR: 192.168.70.132
      GTPU_LOCAL_ADDR: 192.168.70.151
      MCC: 208
      MNC: 98
      TAC: 00ab00
      GNBID: "000003"
      SST_GNB: de
      SST_UE: 222
      SD: "00007b"
      MSIN: "0000000003"
      OPC: 63bfa50ee6523365ff14c1f45f88737d
      KEY: 0C0A34601D4F07677303652C0462535B
      AMF: 8000
      SQN: 0000000
      DNN: oai.ipv4
      NUM_UE: 1
    cap_add:
      - NET_ADMIN
    networks:
      public_net:
          ipv4_address: 192.168.70.151
    healthcheck:
      test: /bin/bash -c "ip addr | grep uetun1"
      interval: 10s
      timeout: 5s
      retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net

